--1
SELECT EMP_NAME, RPAD(SUBSTR(EMP_NO, 1, 8), 14, '*')
FROM EMPLOYEE;

--2
SELECT EMP_NAME, JOB_CODE, TO_CHAR((SALARY + SALARY*NVL(BONUS, 0))*12, 'L999,999,999') || '원' "보너스포함연봉(원)"
FROM EMPLOYEE;

--3
SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE DEPT_CODE IN('D5', 'D9');

--4
SELECT EMP_NAME, HIRE_DATE, LAST_DAY(HIRE_DATE) - HIRE_DATE
FROM EMPLOYEE;

--5
SELECT EMP_NAME, DEPT_CODE, SUBSTR(EMP_NO, 1, 2) || '년' || SUBSTR(EMP_NO, 3, 2) || '월' || SUBSTR(EMP_NO, 5, 2) || '일'
FROM EMPLOYEE;

--6
SELECT EMP_NAME, DEPT_CODE, DECODE(DEPT_CODE, 'D5', '총무부', 'D6', '기획부', 'D9', '영업부')
FROM EMPLOYEE;

SELECT EMP_NAME, DEPT_CODE, 
        CASE DEPT_CODE
            WHEN 'D5' THEN '총무부'
            WHEN 'D6' THEN '기획부'
            WHEN 'D9' THEN '영업부'
        END
FROM EMPLOYEE;        