--3
SELECT BOOK_NO, BOOK_NM
FROM TB_BOOK
WHERE LENGTH(BOOK_NM) >= 25;

--4
SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO
  FROM (SELECT *
          FROM TB_WRITER
         WHERE MOBILE_NO LIKE '019%'
           AND WRITER_NM LIKE '김%'
        ORDER BY WRITER_NM)
 WHERE ROWNUM = 1;  

--5
SELECT COUNT(DISTINCT WRITER_NM) "작가(명)"
  FROM TB_BOOK_AUTHOR
  JOIN TB_WRITER USING (WRITER_NO)
 WHERE COMPOSE_TYPE = '옮김'; 
 
--6
SELECT COMPOSE_TYPE, COUNT(*)
  FROM TB_BOOK_AUTHOR
 WHERE COMPOSE_TYPE IS NOT NULL  
GROUP BY COMPOSE_TYPE
HAVING COUNT(*) >= 300;

--7
SELECT BOOK_NM, ISSUE_DATE, PUBLISHER_NM
  FROM (SELECT *
          FROM TB_BOOK
        ORDER BY ISSUE_DATE DESC)
 WHERE ROWNUM = 1;

--8
SELECT *
  FROM (SELECT WRITER_NM "작가 이름", COUNT(BOOK_NO) "권 수"
          FROM TB_WRITER
          JOIN TB_BOOK_AUTHOR USING(WRITER_NO)
        GROUP BY WRITER_NM
        ORDER BY 2 DESC)
WHERE ROWNUM <= 3;

--9
UPDATE TB_WRITER W
   SET REGIST_DATE = (SELECT MIN(ISSUE_DATE)
                        FROM TB_BOOK
                        JOIN TB_BOOK_AUTHOR USING(BOOK_NO)
                        JOIN TB_WRITER USING(WRITER_NO)
                      GROUP BY WRITER_NM
                      HAVING WRITER_NM = W.WRITER_NM);
COMMIT;
--10
CREATE TABLE TB_BOOK_TRANSLATOR(
    BOOK_NO VARCHAR2(10) CONSTRAINT FK_BOOK_TRANSLATOR_01 REFERENCES TB_BOOK,
    WRITER_NO VARCHAR2(10) CONSTRAINT FK_BOOK_TRANSLATOR_02 REFERENCES TB_WRITER,
    TRANS_LANG VARCHAR2(6),
    CONSTRAINT PK_BOOK_TRANSLATOR PRIMARY KEY(BOOK_NO, WRITER_NO)
);

--11
INSERT INTO TB_BOOK_TRANSLATOR(BOOK_NO, WRITER_NO)
SELECT BOOK_NO, WRITER_NO
  FROM TB_BOOK_AUTHOR
 WHERE COMPOSE_TYPE IN ('옮김', '역주', '편역', '공역'); 
 
DELETE FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE IN ('옮김', '역주', '편역', '공역'); 

--12
SELECT BOOK_NM, WRITER_NM
  FROM TB_BOOK_TRANSLATOR
  JOIN TB_BOOK USING(BOOK_NO)
  JOIN TB_WRITER USING(WRITER_NO)
 WHERE EXTRACT(YEAR FROM ISSUE_DATE) = 2007;

--13
GRANT CREATE VIEW TO WORKSHOP;

CREATE OR REPLACE VIEW VW_BOOK_TRANSLATOR
AS SELECT BOOK_NM, WRITER_NM, ISSUE_DATE
  FROM TB_BOOK_TRANSLATOR
  JOIN TB_BOOK USING(BOOK_NO)
  JOIN TB_WRITER USING(WRITER_NO)
 WHERE EXTRACT(YEAR FROM ISSUE_DATE) = 2007
WITH CHECK OPTION;

--14
INSERT INTO TB_PUBLISHER VALUES('춘 출판사', '02-6710-3737', DEFAULT);
COMMIT;

--15
SELECT WRITER_NM, COUNT(*)
  FROM TB_WRITER
GROUP BY WRITER_NM
HAVING COUNT(*) >= 2;

--16
UPDATE TB_BOOK_AUTHOR
   SET COMPOSE_TYPE = '지음'
 WHERE COMPOSE_TYPE IS NULL;  
COMMIT;

--17
SELECT WRITER_NM, OFFICE_TELNO
  FROM TB_WRITER
 WHERE OFFICE_TELNO LIKE '02-___-%';
 
--18
SELECT WRITER_NM
  FROM TB_WRITER 
 WHERE MONTHS_BETWEEN(TO_DATE('20060101'), REGIST_DATE) / 12 >= 31
 ORDER BY 1;

--19
SELECT BOOK_NM, PRICE
     , CASE WHEN STOCK_QTY < 5 THEN '추가주문필요' 
       ELSE '소량보유'
       END "재고상태"
  FROM TB_BOOK
  JOIN TB_PUBLISHER USING(PUBLISHER_NM)
 WHERE STOCK_QTY < 10
   AND PUBLISHER_NM = '황금가지'
ORDER BY STOCK_QTY DESC, 1; 

--20
SELECT BOOK_NM "도서명", W1.WRITER_NM "저자", W2.WRITER_NM "역자"
  FROM TB_BOOK B
  JOIN TB_BOOK_AUTHOR BA ON(B.BOOK_NO = BA.BOOK_NO)
  JOIN TB_BOOK_TRANSLATOR BT ON(B.BOOK_NO = BT.BOOK_NO)
  JOIN TB_WRITER W1 ON(W1.WRITER_NO = BA.WRITER_NO)
  JOIN TB_WRITER W2 ON(W2.WRITER_NO = BT.WRITER_NO)
 WHERE BOOK_NM = '아타트롤';
 
--21
SELECT BOOK_NM "도서명", STOCK_QTY "재고수량", PRICE "가격(Org)", PRICE * 0.8 "가격(NEW)"
  FROM TB_BOOK
 WHERE MONTHS_BETWEEN(SYSDATE, ISSUE_DATE) >= 360
   AND STOCK_QTY >= 90
ORDER BY 2 DESC, 4 DESC, 1;