--1)
SELECT EMP_NAME "사원명", TO_CHAR(HIRE_DATE, 'YYYY-MM-DD (DY)') "입사일", DEPT_CODE "부서코드", JOB_CODE "직급코드"
FROM EMPLOYEE
ORDER BY 1;

--2) 
SELECT EMP_NAME "사원명", EMP_NO "주민번호", JOB_CODE "직급코드", SALARY "급여", BONUS "보너스", EMAIL "이메일"
FROM EMPLOYEE
WHERE JOB_CODE IN ('J7', 'J6')
  AND SALARY >= 2000000
  AND BONUS IS NOT NULL
  AND SUBSTR(EMAIL, 5, 1) = '_';
  
--3)
SELECT DEPT_ID "부서코드", DEPT_TITLE "부서명"
FROM DEPARTMENT
WHERE LOCATION_ID IN ('L1', 'L2')
  AND DEPT_TITLE NOT LIKE '해외영업%';
  
--4)
SELECT EMP_NAME "사원명", DEPT_TITLE "부서명", JOB_NAME "직급명"
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE E.DEPT_CODE = D.DEPT_ID
  AND E.JOB_CODE = J.JOB_CODE
  AND DEPT_TITLE = '총무부';

SELECT EMP_NAME "사원명", DEPT_TITLE "부서명", JOB_NAME "직급명"
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE DEPT_TITLE = '총무부';

--5) 
SELECT EMP_NAME "사원명", JOB_NAME "직급명", DEPT_CODE "부서코드", DEPT_TITLE "부서명"
FROM EMPLOYEE E, JOB J, DEPARTMENT D
WHERE E.JOB_CODE = J.JOB_CODE
  AND E.DEPT_CODE = D.DEPT_ID
  AND DEPT_TITLE LIKE '해외영업%';
   
SELECT EMP_NAME "사원명", JOB_NAME "직급명", DEPT_CODE "부서코드", DEPT_TITLE "부서명"
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE DEPT_TITLE LIKE '해외영업%';

--6) 
SELECT EMP_NAME "사원명", DEPT_TITLE "부서명", LOCAL_NAME "근무지역명"
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L, NATIONAL N
WHERE E.DEPT_CODE = D.DEPT_ID
  AND D.LOCATION_ID = L.LOCAL_CODE
  AND L.NATIONAL_CODE = N.NATIONAL_CODE
  AND NATIONAL_NAME = '한국';
    
SELECT EMP_NAME "사원명", DEPT_TITLE "부서명", LOCAL_NAME "근무지역명"
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
JOIN NATIONAL USING(NATIONAL_CODE)
WHERE NATIONAL_NAME = '한국';
 
--7) 
SELECT EMP_NAME "사원명", JOB_NAME "직급명"
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
  AND E.JOB_CODE = (SELECT JOB_CODE
                    FROM EMPLOYEE
                   WHERE EMP_NAME = '박나라')
  AND EMP_NAME != '박나라';                   
   
SELECT EMP_NAME "사원명", JOB_NAME "직급명"
FROM EMPLOYEE E
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
WHERE E.JOB_CODE = (SELECT JOB_CODE
                    FROM EMPLOYEE
                   WHERE EMP_NAME = '박나라')
  AND EMP_NAME != '박나라';    

--8) TEST 라는 이름의 새로운 계정을 생성하려고 한다. 이때 관리자계정에서 실행시켜야되는 계정생성 구문과 최소한의 권한을 부여하는 구문을 작성하시오. 
CREATE USER TEST IDENTIFIED BY TEST;
GRANT CONNECT, RESOURCE TO TEST;